package:
  name: sympy-release
  version: 7.0

requirements:
  run:
    - python
    - mpmath
    # Not strictly needed, but it's useful
    - ipython
    # The whole thing is done in vagrant
    - vagrant
    # The release script uses fabric to communicate with vagrant
    - fabric
    - fabric-virtualenv
    # Needed to upload to GitHub
    - requests
    - requests-oauthlib
    # requests must have these installed to support SNI, which GitHub requires
    - urllib3
    - ndg-httpsclient
    - pyasn1
    - pyopenssl
    # Needed to build the website
    - babel
    - jinja2

about:
  license: BSD
  summary: "All the things needed to make a release of SymPy."
